name: 'Run Python linter and pytests'
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - 'data-pipeline/app/**'

jobs:
  lint_and_test:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["2.7", "3.6"]

    defaults:
      run:
        working-directory: data-pipeline/app

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@master
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 --config .flake8
      - name: Test with pytest
        run: |
          python -m pytest -vv
